#include "uart_driver.h"

int main() { 
    UART_init(UART0, 115200);
    // UART_init((UART_t * )0x40070000UL, 115200) // equivalent of above line for learning purposes
    uint8_t count = 0;
    // just there because i want something to do while gdbing
    while (count < 100) {
        count++;
    }
 
}

// taken from uart.h of the pico sdk
static uint32_t UART_disable_before_lcr_write(UART_t *uart) {
    // Notes from PL011 reference manual:
    //
    // - Before writing the LCR, if the UART is enabled it needs to be
    //   disabled and any current TX + RX activity has to be completed
    //
    // - There is a BUSY flag which waits for the current TX char, but this is
    //   OR'd with TX FIFO !FULL, so not usable when FIFOs are enabled and
    //   potentially nonempty
    //
    // - FIFOs can't be set to disabled whilst a character is in progress
    //   (else "FIFO integrity is not guaranteed")
    //
    // Combination of these means there is no general way to halt and poll for
    // end of TX character, if FIFOs may be enabled. Either way, there is no
    // way to poll for end of RX character.
    //
    // So, insert a 15 Baud period delay before changing the settings.
    // 15 Baud is comfortably higher than start + max data + parity + stop.
    // Anything else would require API changes to permit a non-enabled UART
    // state after init() where settings can be changed safely.
    uint32_t cr_save = uart->cr;

    if (cr_save & UART_UARTCR_UARTEN_BITS) {
        uart->cr &= ~(UART_UARTCR_UARTEN_BITS | UART_UARTCR_TXE_BITS | UART_UARTCR_RXE_BITS);
        // hw_clear_bits(uart->cr,
        //     UART_UARTCR_UARTEN_BITS | UART_UARTCR_TXE_BITS | UART_UARTCR_RXE_BITS);

        uint32_t current_ibrd = uart->ibrd;
        uint32_t current_fbrd = uart->fbrd;

        // Note: Maximise precision here. Show working, the compiler will mop this up.
        // Create a 16.6 fixed-point fractional division ratio; then scale to 32-bits.
        uint32_t brdiv_ratio = 64u * current_ibrd + current_fbrd;
        brdiv_ratio <<= 10;
        // 3662 is ~(15 * 244.14) where 244.14 is 16e6 / 2^16
        uint32_t scaled_freq = UART_clock_get_hz(uart) / 3662ul;
        uint32_t wait_time_us = brdiv_ratio / scaled_freq;
        busy_wait_us(wait_time_us);
    }

    return cr_save;
}

static void UART_write_lcr_bits_masked(UART_t *uart, uint32_t values, uint32_t write_mask) {
    // invalid_params_if(HARDWARE_UART, uart != uart0 && uart != uart1);

    // (Potentially) Cleanly handle disabling the UART before touching LCR
    uint32_t cr_save = UART_disable_before_lcr_write(uart);

    uart->lcr_h = values | write_mask;
    // hw_write_masked(&uart_get_hw(uart)->lcr_h, values, write_mask);

    uart->cr = cr_save;
}



void UART_init(UART_t *uart, uint32_t baud_rate) {
    // consider implementing resets.h and gpio.h myself but it sounds like a lot of work
    // also this only applies to UART0 so look into that too
    hw_clear_bits(&resets_hw->reset, RESETS_RESET_UART0_BITS);

    while (!(resets_hw->reset_done & RESETS_RESET_UART0_BITS)) {
        // do nothing
    }

    // baud rate calculations
    uint32_t baud_rate_div = (8 * UART_clock_get_hz(uart) / baud_rate) + 1;
    
    // integer part of baud rate divisor
    uint32_t baud_ibrd = baud_rate_div >> 7; 

    // float part of baud rate divisor
    uint32_t baud_fbrd;

    if (baud_ibrd == 0) {
        baud_ibrd = 1;
        baud_fbrd = 0;
    } else if (baud_ibrd >= 65535) {
        baud_ibrd = 65535;
        baud_fbrd = 0;
    } else {
        baud_fbrd = (baud_rate_div & 0x7f) >> 1;
    }

    // TODO: haven't tested if this is the correct way to access memory yet
    uart->ibrd = baud_ibrd;
    uart->fbrd = baud_fbrd;

    /*
     PL011 Reference Manual, Section 3, Page 14
     The UARTLCR_H, UARTIBRD, and UARTFBRD registers form the single 30-bit
     wide UARTLCR Register that is updated on a single write strobe generated by a
     UARTLCR_H write. So, to internally update the contents of UARTIBRD or
     UARTFBRD, a UARTLCR_H write must always be performed at the end.
    */
    UART_write_lcr_bits_masked(uart, 0, 0);

    // not right :(
    uart->lcr_h = 0;

    // baud = (4 * uart_clock_get_hz(uart)) / (64 * baud_ibrd + baud_fbrd);

    // // TODO: MAKE GOOD CONSTANTS FOR BITS
    // // allow 8 data bits per frame, and enable TX & RX FIFOs
    // uart->lcr_h = UART_UARTLCR_H_WLEN_BITS, UART_UARTLCR_H_FEN_BITS;

    // // enable uart peripheral, and TX & RX bits
    // uart->cr = UART_UARTCR_UARTEN_BITS | UART_UARTCR_TXE_BITS | UART_UARTCR_RXE_BITS;
}

//  ---- EVERYTHING BELOW IS OLD CODE THAT IM ONLY LEAVING FOR REFERENCE!!

// come up with better naming convention too

// void custom_uart_init(uart_inst_t *uart, uint32_t baud_rate) {
//     // don't let code compile if uart doens't point to an actual uart peripheral
//     invalid_params_if(HARDWARE_UART, uart != uart0 && uart != uart1);

//     // gotta find a better way to do this, than a busy wait
//     hw_clear_bits(&resets_hw->reset, RESETS_RESET_UART0_BITS);
//     while (!(resets_hw->reset_done & RESETS_RESET_UART0_BITS)) {
//         // do nothing
//     }

//     uint32_t baud = custom_uart_set_baud_rate(uart, baud_rate);

//     // allow 8 data bits per frame, and enable TX & RX FIFOs
//     uart_get_hw(uart)->lcr_h = UART_UARTLCR_H_WLEN_BITS, UART_UARTLCR_H_FEN_BITS;

//     // enable uart peripheral, and TX & RX bits
//     uart_get_hw(uart)->cr = UART_UARTCR_UARTEN_BITS | UART_UARTCR_TXE_BITS | UART_UARTCR_RXE_BITS;
// }

// int custom_uart_set_baud_rate(uart_inst_t *uart, uint32_t baud_rate) {
//     // don't let code compile if baudrate is 0
//     invalid_params_if(HARDWARE_UART, baud_rate == 0);
//     uint32_t baud_rate_div = (8 * uart_clock_get_hz(uart) / baud_rate) + 1;
    

//     // integer part of baud rate divisor
//     uint32_t baud_ibrd = baud_rate_div >> 7; 

//     // float part of baud rate divisor
//     uint32_t baud_fbrd;

//     if (baud_ibrd == 0) {
//         baud_ibrd = 1;
//         baud_fbrd = 0;
//     } else if (baud_ibrd >= 65535) {
//         baud_ibrd = 65535;
//         baud_fbrd = 0;
//     } else {
//         baud_fbrd = (baud_rate_div & 0x7f) >> 1;
//     }
    
//     uart_get_hw(uart)->ibrd = baud_ibrd;
//     uart_get_hw(uart)->fbrd = baud_fbrd;


//     uart_get_hw(uart)->lcr_h = 0;

//     return (4 * uart_clock_get_hz(uart)) / (64 * baud_ibrd + baud_fbrd);
// }